export const meals = [
    {
    id: "1",
    category: "starters",
    mealName: "Meal 1",
    price: "130",
    info: "Lorem ipsum bla bla bla",
},
{
    id: "2",
    category: "starters",
    mealName: "Meal 2",
    price: "150",
    info: "Lorem ipsum bla bla bla",
},
{   
    id: "3",
    category: "mains",
    mealName: "Meal 3",
    price: "230",
    info: "Lorem ipsum bla bla bla",
},
{ 
    id: "4",
    category: "mains",
    mealName: "Meal 4",
    price: "130",
    info: "Lorem ipsum bla bla bla",
},
{   
    id: "5",
    category: "desserts",
    mealName: "Meal 5",
    price: "130",
    info: "Lorem ipsum bla bla bla",  
},
{   
    id: "6",
    category: "desserts",
    mealName: "Meal 6",
    price: "500",
    info: "Lorem ipsum bla bla bla",
},
{   
    id: "7",
    category: "desserts",
    mealName: "Meal 7",
    price: "500",
    info: "Lorem ipsum bla bla bla",
},
{   
    id: "8",
    category: "desserts",
    mealName: "Meal 7",
    price: "500",
    info: "Lorem ipsum bla bla bla",
},
{   
    id: "9",
    category: "drinks",
    mealName: "Coca cola light",
    price: "500",
    info: "Lorem ipsum bla bla bla",
},
{   
    id: "10",
    category: "drinks",
    mealName: "Coca cola normal",
    price: "500",
    info: "Lorem ipsum bla bla bla",
},
]